import { Listing } from '@/types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Modern Studio in Downtown',
    description: 'Beautiful modern studio apartment in the heart of downtown. Walking distance to all amenities, shops, and restaurants. Perfect for young professionals or students.',
    price: 1200,
    location: {
      city: 'San Francisco',
      state: 'CA',
      address: '123 Market St',
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    roomType: 'entire',
    amenities: ['WiFi', 'Kitchen', 'Laundry', 'Air Conditioning', 'Heating', 'Parking'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    ownerId: 'owner1',
    ownerName: 'John Smith',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    bedrooms: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    availableFrom: '2024-02-01',
    createdAt: '2024-01-15',
    featured: true,
  },
  {
    id: '2',
    title: 'Cozy Private Room in Shared Apartment',
    description: 'Comfortable private room in a shared 3-bedroom apartment. Friendly roommates, quiet neighborhood, close to public transport.',
    price: 750,
    location: {
      city: 'New York',
      state: 'NY',
      address: '456 Broadway Ave',
      coordinates: { lat: 40.7128, lng: -74.0060 },
    },
    roomType: 'private',
    amenities: ['WiFi', 'Kitchen', 'Laundry', 'Heating', 'Shared Bathroom'],
    images: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
    ],
    ownerId: 'owner2',
    ownerName: 'Sarah Johnson',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bedrooms: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    availableFrom: '2024-02-15',
    createdAt: '2024-01-20',
    featured: false,
  },
  {
    id: '3',
    title: 'Spacious 2-Bedroom Apartment',
    description: 'Large 2-bedroom apartment with balcony and city views. Modern kitchen, in-unit washer/dryer, pet-friendly building.',
    price: 2100,
    location: {
      city: 'Los Angeles',
      state: 'CA',
      address: '789 Sunset Blvd',
      coordinates: { lat: 34.0522, lng: -118.2437 },
    },
    roomType: 'entire',
    amenities: ['WiFi', 'Kitchen', 'Laundry', 'Air Conditioning', 'Heating', 'Parking', 'Balcony', 'Pet Friendly'],
    images: [
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    ownerId: 'owner3',
    ownerName: 'Michael Chen',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    bedrooms: 2,
    bathrooms: 2,
    maxOccupancy: 4,
    availableFrom: '2024-03-01',
    createdAt: '2024-01-10',
    featured: true,
  },
  {
    id: '4',
    title: 'Shared Room in Student Housing',
    description: 'Affordable shared room perfect for students. Close to university campus, study areas, and public transportation.',
    price: 450,
    location: {
      city: 'Boston',
      state: 'MA',
      address: '321 College Ave',
      coordinates: { lat: 42.3601, lng: -71.0589 },
    },
    roomType: 'shared',
    amenities: ['WiFi', 'Kitchen', 'Laundry', 'Heating', 'Study Area', 'Shared Bathroom'],
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    ownerId: 'owner4',
    ownerName: 'Emily Davis',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    bedrooms: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    availableFrom: '2024-02-01',
    createdAt: '2024-01-18',
    featured: false,
  },
  {
    id: '5',
    title: 'Luxury Penthouse Downtown',
    description: 'Stunning penthouse with panoramic city views. High-end finishes, rooftop access, concierge service.',
    price: 3500,
    location: {
      city: 'Chicago',
      state: 'IL',
      address: '555 Lake Shore Dr',
      coordinates: { lat: 41.8781, lng: -87.6298 },
    },
    roomType: 'entire',
    amenities: ['WiFi', 'Kitchen', 'Laundry', 'Air Conditioning', 'Heating', 'Parking', 'Balcony', 'Gym', 'Pool', 'Concierge'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    ownerId: 'owner5',
    ownerName: 'David Wilson',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    bedrooms: 3,
    bathrooms: 3,
    maxOccupancy: 6,
    availableFrom: '2024-03-15',
    createdAt: '2024-01-05',
    featured: true,
  },
  {
    id: '6',
    title: 'Charming Private Room in House',
    description: 'Private room in a beautiful house with backyard. Quiet neighborhood, great for remote workers.',
    price: 900,
    location: {
      city: 'Austin',
      state: 'TX',
      address: '888 Oak Street',
      coordinates: { lat: 30.2672, lng: -97.7431 },
    },
    roomType: 'private',
    amenities: ['WiFi', 'Kitchen', 'Laundry', 'Air Conditioning', 'Heating', 'Backyard', 'Parking'],
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
      'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800',
    ],
    ownerId: 'owner6',
    ownerName: 'Lisa Anderson',
    ownerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    bedrooms: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    availableFrom: '2024-02-20',
    createdAt: '2024-01-22',
    featured: false,
  },
];
